// Allowed email domains for sign up and sign in
const ALLOWED_DOMAINS = [
  '.com',
  '.co',
  '.io',
  '.net',
  '.org',
  '.ai',
  '.dev',
  '.app',
  '.tech'
];

// List of common disposable email domains
// This is a curated list of known disposable email services
const DISPOSABLE_DOMAINS = [
  '10minutemail.com',
  '10minutemail.net',
  '2prong.com',
  '33mail.com',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.net',
  'guerrillamail.org',
  'mailinator.com',
  'maildrop.cc',
  'tempmail.org',
  'temp-mail.org',
  'yopmail.com',
  'throwaway.email',
  'getnada.com',
  'mailnesia.com',
  'trashmail.com',
  'sharklasers.com',
  'grr.la',
  'guerrillamail.biz',
  'guerrillamail.info',
  'spam4.me',
  'getairmail.com',
  'fakeinbox.com',
  'emailondeck.com',
  'mohmal.com',
  'my10minutemail.com',
  'mytrashmail.com',
  'emailfake.com',
  'dispostable.com',
  'mintemail.com',
  'spambox.us',
  'mail-temporaire.fr',
  'jetable.org',
  'trbvm.com',
  'toomail.biz',
  'temp-mail.ru',
  'mailbox.in.ua',
  'tempinbox.com',
  'disposableemailaddresses.com',
  'garbagemail.org',
  'meltmail.com',
  'temporarily.de',
  'suremail.info',
  'deadaddress.com',
  'sneakemail.com',
  'filzmail.com',
  'trash-mail.at',
  'trash2009.com',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  '20minutemail.com',
  'emailtemporanea.com',
  'tempemails.net',
  '0-mail.com',
  'incognitomail.org',
  'emailisvalid.com',
  'mailcatch.com',
  'maildu.de',
  'dudmail.com',
  'fakemail.fr',
  'dacoolest.com',
  'tempr.email',
  'tempail.com',
  'tempemail.biz',
  'tempemail.com',
  'receivemails.com',
  'emaildrop.io',
  'emailproxsy.com',
  'thankyou2010.com',
  'emailable.com',
  'tempemailer.com',
  'tempmailaddress.com',
  'tempmailid.com',
  'mailed.in',
  'tempmails.net',
  'zetmail.com',
  'mail.by',
  'mailtothis.com',
  'jourrapide.com',
  'rhyta.com',
  'armyspy.com',
  'cuvox.de',
  'dayrep.com',
  'einrot.com',
  'fleckens.hu',
  'gustr.com',
  'jourrapide.com',
  'superrito.com',
  'teleworm.us',
  'tempsky.com',
  'klzlk.com',
  'moburl.com',
  'luxusmail.org',
  'xtang.com',
  'doanart.com',
  'courriel.fr.nf',
  'tmail.ws',
  'boximail.com',
  'clipmail.eu',
  'correo.blogos.net',
  'dingbone.com',
  'dispomail.eu',
  'dropcake.de',
  'dumpmail.de',
  'einmalmail.de',
  'email60.com',
  'emaildienst.de',
  'emailgo.de',
  'emailmiser.com',
  'emailto.de',
  'emailwarden.com',
  'fakemail.fr',
  'fakemailz.com',
  'fastmail.fm',
  'fast-email.com',
  'fastemailer.com',
  'flemail.ru',
  'flyspam.com',
  'freemail.ms',
  'fremail.hu',
  'fugitive.org.ua',
  'goemailgo.com',
  'gotmail.org',
  'great-host.in',
  'gschwa.de',
  'gustr.com',
  'h8s.org',
  'hidemail.de',
  'hochsitze.com',
  'hulapla.de',
  'imails.info',
  'inboxstore.me',
  'incognitomail.com',
  'insorg-mail.info',
  'instant-mail.de',
  'ipoo.org',
  'irish2me.com',
  'iwi.net',
  'kaspop.com',
  'keepmymail.com',
  'klzlk.com',
  'kurzepost.de',
  'lcg.de',
  'leeching.net',
  'lifebyfood.com',
  'link2mail.net',
  'litedrop.com',
  'lookugly.com',
  'lopl.co.cc',
  'lortemail.dk',
  'lr78.com',
  'lroid.com',
  'lukop.dk',
  'mail-filter.com',
  'mail-temporaire.fr',
  'mail.by',
  'mail.mezimages.net',
  'mail.zp.ua',
  'mail4trash.com',
  'mailbidon.com',
  'mailblocks.com',
  'mailbucket.org',
  'mailcatch.com',
  'maileater.com',
  'mailed.in',
  'mailed.ro',
  'mailexpire.com',
  'mailforspam.com',
  'mailfreeonline.com',
  'mailguard.me',
  'mailin8r.com',
  'mailinater.com',
  'mailinator.com',
  'mailinator.net',
  'mailinator.org',
  'mailinator2.com',
  'mailincubator.com',
  'mailismagic.com',
  'mailme.lv',
  'mailmetrash.com',
  'mailmoat.com',
  'mailnator.com',
  'mailnesia.com',
  'mailnull.com',
  'mailorg.org',
  'mailpick.biz',
  'mailrock.biz',
  'mailscrap.com',
  'mailshell.com',
  'mailsiphon.com',
  'mailtemp.info',
  'mailtome.de',
  'mailtothis.com',
  'mailtrash.net',
  'mailtv.net',
  'mailtv.tv',
  'mailzilla.com',
  'mailzilla.org',
  'makemetheking.com',
  'meltmail.com',
  'messagebeamer.de',
  'mezimages.net',
  'mierdamail.com',
  'mintemail.com',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',
  'mt2009.com',
  'mt2014.com',
  'mypartyclip.de',
  'myphantomemail.com',
  'mysamp.de',
  'mythirdmail.com',
  'myzx.com',
  'netzidiot.de',
  'neverbox.com',
  'nice-4u.com',
  'nincsmail.hu',
  'nospam.ze.tc',
  'nospamfor.us',
  'nospamthanks.info',
  'notmailinator.com',
  'notsharingmy.info',
  'now.im',
  'nullbox.info',
  'objectmail.com',
  'odem.org',
  'odnorazovoe.ru',
  'oneoffemail.com',
  'onewaymail.com',
  'onlatedotcom.info',
  'ordinaryamerican.net',
  'otherinbox.com',
  'ovpn.to',
  'owlpic.com',
  'pancakemail.com',
  'pcusers.otherinbox.com',
  'pjkprime.com',
  'plexolan.de',
  'poczta.onet.pl',
  'politikerclub.de',
  'poofy.org',
  'pookmail.com',
  'privacy.net',
  'privatdemail.net',
  'proxymail.eu',
  'prtnx.com',
  'putthisinyourspamdatabase.com',
  'pw.8hash.com',
  'quickinbox.com',
  'rcpt.at',
  'reallymymail.com',
  'realtyalerts.ca',
  'receiveee.com',
  'receivemails.com',
  'recursor.net',
  'recyclemail.dk',
  'regbypass.com',
  'rmqkr.net',
  'rppkn.com',
  'rtrtr.com',
  'sandboxmail.org',
  'schafmail.de',
  'schrott-email.de',
  'secretemail.de',
  'secure-mail.biz',
  'selfdestructingmail.com',
  'sendspamhere.com',
  'sharedmailbox.org',
  'shitmail.me',
  'shitware.nl',
  'shmeriously.com',
  'shortmail.net',
  'sibmail.com',
  'sinnlos-mail.de',
  'siteposter.net',
  'skeefmail.com',
  'slopsbox.com',
  'smashmail.de',
  'smellfear.com',
  'snakemail.com',
  'snkmail.com',
  'sofimail.com',
  'sofort-mail.de',
  'sofortmail.de',
  'sogetthis.com',
  'soodonims.com',
  'spam.la',
  'spam.su',
  'spam4.me',
  'spamail.de',
  'spambob.com',
  'spambob.net',
  'spambob.org',
  'spambog.com',
  'spambog.de',
  'spambog.ru',
  'spambox.info',
  'spambox.irishspringtours.com',
  'spambox.us',
  'spamcannibal.org',
  'spamcannon.com',
  'spamcannon.net',
  'spamcero.com',
  'spamcon.org',
  'spamcorptastic.com',
  'spamcowboy.com',
  'spamcowboy.net',
  'spamcowboy.org',
  'spamday.com',
  'spamex.com',
  'spamfree24.com',
  'spamfree24.de',
  'spamfree24.eu',
  'spamfree24.net',
  'spamfree24.org',
  'spamgourmet.com',
  'spamgourmet.net',
  'spamgourmet.org',
  'spamherelots.com',
  'spamhereplease.com',
  'spamhole.com',
  'spami.spam.co.za',
  'spaminator.de',
  'spamkill.info',
  'spaml.com',
  'spaml.de',
  'spammotel.com',
  'spamobox.com',
  'spamoff.de',
  'spamsalad.in',
  'spamspot.com',
  'spamstack.net',
  'spamthis.co.uk',
  'spamthisplease.com',
  'spamtrail.com',
  'spamtroll.net',
  'speed.1s.fr',
  'spoofmail.de',
  'stuffmail.de',
  'super-auswahl.de',
  'supergreatmail.com',
  'supermailer.jp',
  'superrito.com',
  'superstachel.de',
  'suremail.info',
  'talkinator.com',
  'tamemail.com',
  'teewars.org',
  'teleworm.com',
  'teleworm.us',
  'temp-mail.org',
  'temp-mail.ru',
  'tempail.com',
  'tempalias.com',
  'tempe-mail.com',
  'tempemail.biz',
  'tempemail.com',
  'tempemail.net',
  'tempemails.net',
  'tempinbox.co.uk',
  'tempinbox.com',
  'tempmail.eu',
  'tempmail2.com',
  'tempmaildemo.com',
  'tempmailer.com',
  'tempmailer.de',
  'tempmailid.com',
  'tempmails.net',
  'tempsky.com',
  'tempymail.com',
  'thankyou2010.com',
  'thecloudindex.com',
  'thisisnotmyrealemail.com',
  'thismail.net',
  'throwawayemailaddresses.com',
  'tilien.com',
  'tittbit.in',
  'tmail.ws',
  'tmailinator.com',
  'toiea.com',
  'toomail.biz',
  'topranklist.de',
  'tradermail.info',
  'trash-amil.com',
  'trash-mail.at',
  'trash-mail.com',
  'trash-mail.de',
  'trash2009.com',
  'trashdevil.com',
  'trashdevil.de',
  'trashemail.de',
  'trashmail.at',
  'trashmail.com',
  'trashmail.de',
  'trashmail.me',
  'trashmail.net',
  'trashmail.org',
  'trashmail.ws',
  'trashmailer.com',
  'trashymail.com',
  'trashymail.net',
  'trbvm.com',
  'turual.com',
  'twinmail.de',
  'tyldd.com',
  'uggsrock.com',
  'umail.net',
  'upliftnow.com',
  'uplipht.com',
  'venompen.com',
  'veryrealemail.com',
  'viditag.com',
  'viewcastmedia.com',
  'viewcastmedia.net',
  'viewcastmedia.org',
  'vubby.com',
  'walkmail.net',
  'webemail.me',
  'webm4il.info',
  'wegwerfadresse.de',
  'wegwerfemail.de',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'wh4f.org',
  'whyspam.me',
  'willselfdestruct.com',
  'winemaven.info',
  'wronghead.com',
  'wuzup.net',
  'wuzupmail.net',
  'www.e4ward.com',
  'www.gishpuppy.com',
  'www.mailinator.com',
  'wwwnew.eu',
  'x.ip6.li',
  'xagloo.com',
  'xemaps.com',
  'xents.com',
  'xmaily.com',
  'xoxy.net',
  'yapped.net',
  'yeah.net',
  'yep.it',
  'yogamaven.com',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'yourdomain.com',
  'yourmailbox.info',
  'yuurok.com',
  'z1p.biz',
  'za.com',
  'zehnminutenmail.de',
  'zetmail.com',
  'zippymail.info',
  'zoemail.org',
  'zomg.info'
];

export interface EmailValidationResult {
  isValid: boolean;
  error?: string;
}

/**
 * Validates if an email domain is allowed for sign up and sign in
 * @param email - The email address to validate
 * @returns EmailValidationResult object with validation status and error message
 */
export function validateEmailDomain(email: string): EmailValidationResult {
  if (!email || typeof email !== 'string') {
    return {
      isValid: false,
      error: 'Email is required'
    };
  }

  // Basic email format validation
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!emailRegex.test(email)) {
    return {
      isValid: false,
      error: 'Please enter a valid email address'
    };
  }

  const emailLower = email.toLowerCase().trim();
  const domain = emailLower.split('@')[1];

  if (!domain) {
    return {
      isValid: false,
      error: 'Please enter a valid email address'
    };
  }

  // Check if it's a disposable email
  if (DISPOSABLE_DOMAINS.includes(domain)) {
    return {
      isValid: false,
      error: 'Disposable email addresses are not allowed. Please use a permanent email address.'
    };
  }

  // Check if the domain ends with any of the allowed TLDs
  const hasAllowedTLD = ALLOWED_DOMAINS.some(allowedTLD => domain.endsWith(allowedTLD));

  if (!hasAllowedTLD) {
    return {
      isValid: false,
      error: 'We detect that you are using a domain that is not allowed by our system. Please use an email with one of these domains: .com, .co, .io, .net, .org, .ai, .dev, .app, .tech'
    };
  }

  return {
    isValid: true
  };
}

/**
 * Additional validation for Google OAuth emails
 * This can be used to validate emails from Google sign-in
 * @param email - The email from Google OAuth
 * @returns EmailValidationResult
 */
export function validateGoogleEmail(email: string): EmailValidationResult {
  return validateEmailDomain(email);
} 